apiVersion: v1
kind: Service
metadata:
  name: python-guestbook-backend
  labels:
    app: python-guestbook
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: python-guestbook
    tier: backend
  ports:
  - name: http
    port: 5002
    targetPort: 5002