apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-guestbook-backend
  labels:
    app: python-guestbook
    tier: backend
spec:
  replicas: 1 # Usually in production, we set replicas to 3 or 5 for higher availability and resilience to failures.
  selector:
    matchLabels:
      app: python-guestbook
      tier: backend
  template:
    metadata:
      labels:
        app: python-guestbook
        tier: backend
    spec:
      initContainers:
      - name: init-db-ready
        image: mongo:4
        command: ['/bin/sh', '-c']
        args:
          - echo "Waiting for mongodb at python-guestbook-mongodb:27017 to go live before the BE..."; 
          - until (mongo --host python-guestbook-mongodb:27017 >/dev/null) do echo "Waiting for connection for 2 sec."; sleep 2; done
      containers:
      - name: backend
        image: localhost:5000/guestbook-backend
        ports:
        - containerPort: 5002
        env:
        - name: PORT
          value: "5002"
        - name: GUESTBOOK_DB_ADDR
          value: "python-guestbook-mongodb:27017"
