apiVersion: v1
kind: Service
metadata:
  name: python-guestbook-frontend
  labels:
    app: python-guestbook
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: python-guestbook
    tier: frontend
  ports:
  - name: http-port
    port: 5001
    targetPort: 5001